name: Clean workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /afs/glue.umd.edu/home/glue/l/t/ltuck99/pub/cmsc389T-web-template
            unalias rm
            rm -rf cmsc389T-web-template